apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Petstore Swagger API
spec:
  type: openapi
  lifecycle: production
  owner: team-platform
  definition:
    $text: https://petstore3.swagger.io/api/v3/openapi.json
