apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: chris.mortin
  description: Senior Platform Engineer

spec:
  profile:
    displayName: Chris Mortin
    email: chris.mortin@example.com
    picture: https://example.com/chris-dng.png

  memberOf:
    - platform-team
    - devops-team
